version: '3'
services: 
  api: 
    image: utilize
    build: .
    networks:
      - backend
    ports:
      - "8000:8000"
  
  web-cli:
    image: utilize
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge