version: '3'
services: 
  api: 
    image: utilize
    build: .
    networks:
      - backend
    ports:
      - "8000:8000"
  
  db:
    image: mongo:latest
    restart: always
    volumes: 
      - ./utilizeData:\mongodb\data
    environment:
      - MONGO_INITDB_DATABASE= utilize
    ports:
      - 27017:27017

  web-cli:
    image: utilize
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge