version: '3'
services: 
  api: 
    image: utilize
    build: .
    networks:
      - backend
    ports:
      - "8000:8000"
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: resparx
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web-cli:
    image: utilize
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge