version: '3'
services: 
  api: 
    image: utilize
    build: .
    networks:
      - backend
    ports:
      - "8000:8000"
  
  db:
    image: postgres
    restart: always
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}

networks:
  backend:
    driver: bridge